{
 "title": "Rocket 1.0",
 "time": { "from": "2024-07-24T13:08:07.577Z", "to": "2024-07-24T13:10:49.876Z" },
 "panels": [
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"Rocket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"altitude\")\r\n\r\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 7, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Rocket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"lon\" or r[\"_field\"] == \"lat\")\r\n"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "targets": [
    {
     "query": "from(bucket: \"Rocket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"accel\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "accMS2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Rocket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"accel\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"Rocket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n\r\n"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Rocket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\r\n\r\n"
    }
   ]
  }
 ]
}